### PR TITLE
Nyt article

### PR DESCRIPTION
**Pull request by Addis-Belete**
The New York Times Article
This project is mainly focused in building the replica of New York times article page.  Html and CSS languages were used to build this project.

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Changes Required
Hello @Addis0943, You are making good progress on this project. Most of the designs are taking shape :muscle: 
Some changes to be made though, before approval :point_down: 
#### Navigation bar
- [x] The NYT image logo looks stretched. I think you can improve on it.
- [x] Ensure that the image logo and the text next to the search icons are links
- [x] Ensure that you have a `Log in` button it the rightmost side. add a border-radius to make them more like the original design
- [x] The navigation bar seems to be transparent and I can see through while scrolling. Kindly fix it and ensure that it behaves like the original page.
- [x] There should be some margin below the navigation. Between the Navigation and the first header

#### Main
- [x] The first header and the social media icons section Should be aligned
#### The Theory of Inflation
- [x] Check the image size and ensure that there is the text description below each image as in the original design. Currently, the descriptions are stuck on top of each other and some are overflowing.
#### Bottom part
- [x] Ensure that the images use anchor tag, any valid value e.g. "#" is okay for it's `href` attribute, to other articles with image previews
- [x] There is a very big gap before the Most Popular. Kindly fix it.
- [x] Check that you have all the borders. For example above the Editors’ Picks, Most Popular, More Spaces In Astronomy sections
- [x] The NYT logo below is too small, Kindly adjust it
- [x] You should have a double bottom before the NYT logo

## Kindly fix the above issues before submitting another review.
## Feel free to reach me on slack [Oloo Moses] incase of doubts or concerns
# Happy Codding

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are some changes required, please check the comments below._

- ### To Highlight
  - [x] Nice job implementing all of the feedback 💯
- ### To Improve
  - [x] [MANDATORY] Your live-demo link is broken, kindly fix that. 
  - [x] [MANDATORY] This [content](https://res.cloudinary.com/newpoint/image/upload/v1613761566/image/Capture1_shz4cw.png) is overlapping the header and description of this section, kindy fix that. 
  


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on @slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
@slack: Rukundo Eric**

**Review by Forison — CHANGES_REQUESTED** [review]
## Status: Change Required❌

# Hi team

#### Good job on addressing the issue raised in the previous review, the content are no more overlapping and the link in the Readme is fixed. However, there is one issue we have to address to get the project approved😇.

* [x] There is an horizontal scroll on the page, this is due to elements overflowing their parent container, let us address the issue. 
Screenshot from 2021-02-20 03-28-19
> check the bottom of you page
#### That is it kindly make the change and submit a re-review👷

#### Happy coding👨‍💻

Addo Forison

**Review by krys2fa — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this project approved. 👍 

You can now merge this branch into the master branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

All the best @Addis0943,
Chris

**Pull request merged**
